sudo: required
services:
  - docker

before_install:
  - docker build -t xiyuewang/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xiyuewang/react-test npm test

after_success:
  - docker build -t xiyuewang/multi-client ./client
  - docker build -t xiyuewang/multi-nginx ./nginx
  - docker build -t xiyuewang/multi-server ./server
  - docker build -t xiyuewang/multi-worker ./worker
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub 
  - docker push xiyuewang/multi-client
  - docker push xiyuewang/multi-nginx
  - docker push xiyuewang/multi-server
  - docker push xiyuewang/multi-worker
